feat: provide environment variable support
Byzanteam/jet-scaffolds pull request #13
Opened 2022-12-07 10:00 UTC by zxqzy

close #10

2022-12-07 11:06 UTC, moonRider submitted a review, later dismissed

2022-12-08 02:49 UTC, fahchen requested changes

2022-12-08 02:49 UTC, fahchen commented on vue-template/.env.example
> +PUBLIC_PATH=/
文件组织按照 vite 的规则来
https://vitejs.dev/guide/env-and-mode.html#env-files

2022-12-08 04:18 UTC, fahchen approved these changes

2022-12-08 04:20 UTC, moonRider approved these changes

2022-12-08 05:29 UTC, merged