standard deploy flow
Byzanteam/jet-scaffolds pull request #22
Opened 2022-12-27 08:04 UTC by moonRider

2022-12-28 02:36 UTC, vanppo commented on deploy/nginx/start.sh
> +sed -i "s/\/BASE_PLACEHOLDER\//$RUNTIME_BASE_URL/g" ./*
```suggestion
sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./*
```
sed 可以用其他字符作为分隔符 比如 `#` 你试试看呢

2022-12-28 03:23 UTC, fahchen reviewed
https://vitejs.dev/guide/build.html#advanced-base-options

这个不行哇？

2022-12-28 08:06 UTC, moonRider commented
> https://vitejs.dev/guide/build.html#advanced-base-options
> 
> 这个不行哇？

run image 的时候提供的 base 在 renderBuiltUrl 内取不到，还是要在 build 完成后去替换。所以就没用这个 renderBuiltUrl 定义了

2022-12-28 09:55 UTC, fahchen commented
> > https://vitejs.dev/guide/build.html#advanced-base-options
> > 这个不行哇？
> 
> run image 的时候提供的 base 在 renderBuiltUrl 内取不到，还是要在 build 完成后去替换。所以就没用这个 renderBuiltUrl 定义了

为啥取不到啊？

2022-12-28 10:22 UTC, moonRider commented
> > > https://vitejs.dev/guide/build.html#advanced-base-options
> 
> > > 这个不行哇？
> 
> > 
> 
> > run image 的时候提供的 base 在 renderBuiltUrl 内取不到，还是要在 build 完成后去替换。所以就没用这个 renderBuiltUrl 定义了
> 
> 
> 
> 为啥取不到啊？

renderBuiltUrl是在vite build这里就消费了。运行image的时候才能决定最终的base。

2022-12-28 10:27 UTC, fahchen commented
renderBuiltUrl 可以是一个函数，在运行时把函数注入进去就行了吧

2022-12-30 02:38 UTC, fahchen requested changes

2022-12-30 02:38 UTC, fahchen commented on vue-template/public/runtime.js
> +}
这里的值和 `.env` 里面的值没有联动起来哦，如果我改了 `.env` 里面的 `BASE_URL` 这里是不会改的

2022-12-30 02:39 UTC, fahchen commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
你测试下 css 以及 font 相关的路径对不对哦

2022-12-30 03:24 UTC, moonRider commented on vue-template/public/runtime.js
> +}
.env 里面设置 BASE_URL 这种方式不可取，因为我们 build 的时候都会走 BASE_PLACEHOLDER，.env 内的设置只会按照 vite 官方定义的使用方式（有 VITE_ 前缀）

2022-12-30 03:27 UTC, moonRider commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
> 你测试下 css 以及 font 相关的路径对不对哦

测试了的，是ok的，css 和 font 的路径都会定义为相对路径，这个相对路径是相对于应用它的资源的路径来的，所以不会受 vue-router 的影响。受 vue-router 影响的只有 index.html，我们只要保证 index.html 内的路径不是相对路径就没有问题

2022-12-30 05:28 UTC, fahchen commented on vue-template/public/runtime.js
> +}
不应该在 .env 里面设置 base 吗？

2022-12-30 05:30 UTC, fahchen commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
这里用相对路径是可以设置的吗？还是只能是相对路径

2022-12-30 09:05 UTC, moonRider commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
> 这里用相对路径是可以设置的吗？还是只能是相对路径

这个相对路径是 renderBuiltUrl 这个函数设置定义的，这里设置为相对路径是避免 BASE_URL 出现在非 index.html 文件内而设置的。

2023-01-03 03:41 UTC, fahchen commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
`renderBuiltUrl` 设置的值是啥？

2023-01-03 03:43 UTC, fahchen commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
> > 你测试下 css 以及 font 相关的路径对不对哦
> 
> 测试了的，是ok的，css 和 font 的路径都会定义为相对路径，这个相对路径是相对于引用它的资源的路径来的，所以不会受 vue-router 的影响。受 vue-router 影响的只有 index.html，我们只要保证 index.html 内的路径不是相对路径就没有问题

我看了下 font 是根据你的 `BASE` 来的吧，你做一个 demo 的 repo 出来看下

2023-01-03 04:00 UTC, fahchen commented
区分一下 BASE_URL 和 BASE_PATH 哈

2023-01-03 04:00 UTC, fahchen commented on vue-template/public/runtime.js
> +}
.env 文件里面的 BASE 是用来干嘛的？

2023-01-03 07:56 UTC, moonRider commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
> `renderBuiltUrl` 设置的值是啥？

`{ relative: true }`

2023-01-03 08:17 UTC, moonRider commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
https://github.com/moonRider/deploy-template

2023-01-03 09:27 UTC, fahchen commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
> https://github.com/moonRider/deploy-template

你引入一下 font

2023-01-03 09:28 UTC, moonRider commented on deploy/nginx/start.sh
> +sed -i "s#/BASE_PLACEHOLDER/#$RUNTIME_BASE_URL#g" ./index.html
👌

2023-01-03 10:00 UTC, moonRider commented
build 之后的 style.css: 
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/6049820/210335291-c900003f-54fd-46b6-87b1-9010c3765747.png">

结果还是相对路径的形式，符合预期的

2023-01-04 05:55 UTC, moonRider commented
@fahchen

2023-01-04 06:41 UTC, fahchen commented
> @fahchen

https://github.com/Byzanteam/jet-scaffolds/pull/22/files#r1060266223

2023-01-04 06:43 UTC, fahchen commented
没有被 resolve 的 conversation 及时回复

2023-01-04 07:01 UTC, moonRider commented
> 这里的 runtime 不是很好，这里尝试使用 plugin 来生成这部分代码，让环境变量里面的值都通过 plugin 生成的代码来获取，就不走 vite 的那个方式了，这样也能把 actions 配置的问题也解决了

这样会涉及到覆盖 image 里面的文件，这个好操作么

2023-01-04 07:53 UTC, fahchen commented
> > 这里的 runtime 不是很好，这里尝试使用 plugin 来生成这部分代码，让环境变量里面的值都通过 plugin 生成的代码来获取，就不走 vite 的那个方式了，这样也能把 actions 配置的问题也解决了
> 
> 这样会涉及到覆盖 image 里面的文件，这个好操作么

不会覆盖吧，你举例说说

2023-02-03 12:40 UTC, closed without merging