feat: support tailwindss and sass
Byzanteam/jet-scaffolds pull request #37
Opened 2023-02-02 07:33 UTC by zxqzy

2023-02-02 07:51 UTC, moonRider requested changes

2023-02-02 07:51 UTC, moonRider commented on vue/package.json
> +    // @if tailwindcss
sass 也要这个和 postcss. 可能样式那边需要多设计一个 empty choice，如果没有的话，就不要任何 css 的依赖，否则是 sass, tailwindcss 2选1

2023-02-02 07:55 UTC, moonRider requested changes

2023-02-02 07:55 UTC, moonRider commented on vue/src/components/HelloWorld.vue__if_tailwindcss
> +  <h1 class="my-5 text-center text-gray-900">{{ msg }}</h1>
这个用 inline conditional 来处理吧，两个文件有点浪费

2023-02-02 07:55 UTC, moonRider commented on vue/src/style.css__if_sass
> +}
这个留个空文件，甚至不需要这个文件

2023-02-02 07:55 UTC, moonRider commented on vue/package.json
> +    // @if tailwindcss
sass 也需要 postcss 和 autoprefixer

2023-02-02 10:18 UTC, moonRider requested changes

2023-02-02 10:18 UTC, moonRider commented on questions.js
> +        title: 'No',
```suggestion
        title: 'None',
```

2023-02-02 10:18 UTC, moonRider commented on vue/package.json
> +    // @if sass or tailwindcss
```suggestion
    // @if sass || tailwindcss
```

2023-02-02 10:18 UTC, moonRider commented on vue/src/components/HelloWorld.vue
> +  // @if !tailwindcss
```suggestion
  <-- @if !tailwindcss ->
```

2023-02-03 02:06 UTC, zxqzy commented on vue/src/components/HelloWorld.vue
> +  // @if !tailwindcss
这里我试了下不得行，html 文件用这个才行，而这个是 vue 文件

2023-02-03 02:58 UTC, moonRider requested changes

2023-02-03 02:58 UTC, moonRider commented on vue/src/main.ts
> -
这个要保留的，确保 import 语句和 code block 有一个空行

2023-02-03 03:05 UTC, zxqzy commented on vue/src/main.ts
> -
最下面有一个空行，如果这里还有，用 router 末尾就有两个空行

2023-02-03 03:46 UTC, moonRider approved these changes

2023-02-03 03:47 UTC, moonRider approved these changes

2023-02-03 03:47 UTC, merged