feat: support i18n
Byzanteam/jet-scaffolds pull request #56
Opened 2023-02-09 03:19 UTC by zxqzy

close #50

2023-02-09 03:40 UTC, moonRider requested changes
补上 i18n 的 readme
1. 用 example 的 `zh_CN.json` 来介绍怎么使用。
    * 我们定制的额外功能 `__t__` 怎么用的
    * 模版中怎么使用
    * setup 中怎么使用
5. 我想了解更多的话需要在哪里查看文档。

2023-02-09 03:40 UTC, moonRider commented on questions.js
> +    message: 'what features do you want to use for this project?',
```suggestion
    message: 'What features do you want to use for this project?',
```

2023-02-10 11:31 UTC, moonRider approved these changes

2023-02-13 02:45 UTC, zxqzy commented
重做了下 commit

2023-02-13 02:51 UTC, moonRider approved these changes

2023-02-13 02:51 UTC, merged