fix: husky prepare script
Byzanteam/jet-scaffolds pull request #63
Opened 2023-03-21 09:10 UTC by shaddollxz

给 husky 添加 install 脚本，并给下面的文件添加可执行权限

2023-03-21 09:38 UTC, moonRider requested changes

2023-03-21 09:38 UTC, moonRider commented on common/package.json
> +    "prepare": "husky install && chmod +x .husky/*",
不在prepare里面执行，在after.js里面

2023-03-21 10:02 UTC, shaddollxz commented on common/package.json
> +    "prepare": "husky install && chmod +x .husky/*",
> 不在prepare里面执行，在after.js里面

想了下把 husky install 留着，把 chmod 换到 after.js 里合适点

2023-03-22 02:01 UTC, shaddollxz commented on common/package.json
> +    "prepare": "husky install && chmod +x .husky/*",
install 需要每次下载安装的时候把 .husky/_ 里的文件下载，这个文件夹不会被 git 记录的

2023-03-22 02:02 UTC, shaddollxz commented
makes 更新了下版本，需要把 npx 的缓存清了才能使用新版本对 shell 通配符的支持

2023-03-22 02:12 UTC, moonRider approved these changes

2023-03-22 02:12 UTC, moonRider commented
> makes 更新了下版本，需要把 npx 的缓存清了才能使用新版本对 shell 通配符的支持

这个写到 readme 里面

2023-03-22 02:47 UTC, moonRider approved these changes

2023-03-22 02:48 UTC, merged