use shell to skip repeated degit command
Byzanteam/jet-scaffolds pull request #8
Opened 2022-11-07 10:37 UTC by moonRider

close #7

2022-11-07 10:39 UTC, fahchen requested changes

2022-11-07 10:39 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
应该不需要这个判断，直接 force 就好了

2022-11-07 10:40 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
判断可以不用执行文件下载，直接 force 会重复下载文件

2022-11-07 21:11 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
1. 这个判断不准确，比如 .github 文件夹不止用于 workflows
2. 直接覆盖后，通过 git diff 去判断是否要保留更新

2022-11-08 01:38 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
> 1. 这个判断不准确，比如 .github 文件夹不止用于 workflows
> 2. 直接覆盖后，通过 git diff 去判断是否要保留更新

大多数时候应该是不需要再更新模版的。如果真需要更新了，这时用手动更新要更方便点

2022-11-08 01:49 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
这个脚本还会在ci里面跑，ci里面不好处理git diff了

2022-11-08 02:16 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
1. 要不额外加个 force 的参数
2. 为啥要到 ci 里面跑

2022-11-08 02:39 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
> 1. 要不额外加个 force 的参数
> 2. 为啥要到 ci 里面跑

pnpm install 会跑

2022-11-08 03:06 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
那加个额外的参数控制吧

2022-11-08 03:16 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
这样是不是用手动执行的方式要更方便些，本来就只需要按需执行

2022-11-08 03:39 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
手动的话需要去对应的地方把文件打开复制粘贴过来，挺麻烦的

2022-11-08 03:43 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
pnpm有个devPostinstall，这个钩子好像符合我们的预期（仅在本地执行pnpm install时执行）

2022-11-08 03:44 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
你看看呢
我觉得还是要考虑后期升级哈，我们可能会引入更多的东西的

2022-11-08 04:39 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
degit -- force 对文件的合并策略是符合我们预期的，devPreinstall 这个不适合我们的场景。目前看下来我们就两个需求
1. 初始化项目时需要执行 clone 子目录的需要，clone 下来的文件会由开发人员添加进 commit。
2. 如果这些子目录需要更新，或需要更多的东西，此时也需要再执行 degit 去 clone 子目录。
除这2个场景外，其余时刻是不需要执行 clone 任务的，目前看下来是手动执行比较方便呢。
步骤应该是先 clone 整个项目的主体模版，然后根据需要选择需要 clone 的子目录执行子目录的 clone 任务（任务执行完成后需要用户commit）ci 完全不需要执行子目录的 clone 任务

2022-11-08 04:45 UTC, fahchen commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
第二点就看在升级更新的时候，是不是要屏蔽掉 degit 而是使用 script (package.json) 去更新了

2022-11-08 04:48 UTC, moonRider commented on vue-template/script/init.sh
> +if [ ! -d './.github' ]; then
暂时还是认为是 degit 吧。后面如果是 script 去更新，那再来调整这边就是了

2022-11-08 06:30 UTC, fahchen commented on vue-template/package.json
> +    "clone:deploy": "degit git@github.com:Byzanteam/jet-scaffolds/deploy deploy",
`clone` 改成 `setup` 如何？
```suggestion
    “setup:deploy": "degit git@github.com:Byzanteam/jet-scaffolds/deploy deploy",
```

2022-11-08 06:30 UTC, fahchen commented on vue-template/package.json
> +    "clone:configs": "pnpm clone:deploy --force && pnpm clone:git-actions --force && pnpm clone:husky --force",
```suggestion
    "setup:ci": "pnpm clone:deploy --force && pnpm clone:git-actions --force && pnpm clone:husky --force",
```

2022-11-09 00:17 UTC, fahchen approved these changes

2022-11-09 05:30 UTC, merged