feat: nextjs template
Byzanteam/jet-scaffolds pull request #82
Opened 2024-03-28 06:59 UTC by shaddollxz

2024-03-29 06:38 UTC, moonRider requested changes

2024-03-29 06:38 UTC, moonRider commented on next/.env.development
把 buildtime envs 和 runtime envs 定义在这里，列两个 example（注释的形式）

2024-03-29 06:38 UTC, moonRider commented on next/package.json
> +    "@byzanteam/prettier-config": "^1.1.0",
这个 common 里面有了，不用定义，你检查下其它的依赖

2024-03-29 06:38 UTC, moonRider commented on next/src/app/layout.tsx
> +};
这个格式有问题，与 prettier/eslint 的格式是冲突的，你在本地用这个模版生成后跑一次 lint/prettier

2024-04-01 01:58 UTC, shaddollxz commented on next/package.json
> +    "@byzanteam/prettier-config": "^1.1.0",
就这一个地方重复了

2024-04-01 02:09 UTC, moonRider approved these changes

2024-04-01 06:13 UTC, merged